### ISSUE TITLE
`t1flex()` causes errors when more than one header column has the same N

### ISSUE THREAD

**Issue by billdenney** [benjaminrich/table1#103]
In the example below, it seems like duplicate N cause an issue with the flextable creation.

``` r
library(table1)
#> 
#> Attaching package: 'table1'
#> The following objects are masked from 'package:base':
#> 
#>     units, units<-

foo <- data.frame(A = rep(1:2, each = 3), B = rep(1:3, each = 2), C = 1:6)
mytab <- table1(~C|A+B, data = foo)
#> Warning in table1.formula(~C | A + B, data = foo): Terms to the right of '|' in
#> formula 'x' define table columns and are expected to be factors with meaningful
#> labels.
t1flex(mytab)
#> Error in flextable(data): duplicated col_keys: 2
#> (N=1), 1
#> (N=2), 3
#> (N=2)
```

<sup>Created on 2023-03-15 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by benjaminrich** [comment]
Thanks for bringing this to my attention. I wasn't aware of this issue. I'll try to look for a solution.

**Comment by benjaminrich** [comment]
I've found a solution, and created a PR (#105).

**Comment by billdenney** [comment]
Thanks!

**Comment by fthielen** [comment]
@benjaminrich: Is it correct that this is not integrated in the current package version on CRAN (1.4.3)?
Even if I install the latest dev version (1.4.4), the example by @billdenney does not work.

How can I make use of the fix?

**Comment by SilviaMorgenstern** [comment]
Sorry for resuscitating this old post, but I am encountering exactly this issue. I am trying to convert a table created with table1 to flextable and t1flex fails if column names are the same (and they are because of having the same N). I have table1 v. 1.4.3 on R 2024.04.2. The screenshot shows that 0-2 category is N=45 in both strata.
Should not this issue be solved in this version? How can I fix this?

![Image](https://github.com/user-attachments/assets/c27d5c42-489e-4fd8-9249-d5613d8f1028)

**Comment by billdenney** [comment]
@SilviaMorgenstern, Can you make a reprex?

**Comment by SilviaMorgenstern** [comment]
Here is a reprex, I hope it helps! R version 4.4.1, all packages up to date.

`# Load necessary libraries
library(table1)
library(flextable)
library(dplyr)

#Create sample dataset
gender <- factor(c("m","f","m","f","f","f","m","m","f","f"))
age <- c(1,3,3,2,3,2,2,1,1,1)
score <- c(2,3,5,2,2,2,4,4,2,6)
data <- data.frame(gender, age, score)

#Create table
score.t <- table1(~ score | gender+age, data=data, overall="Total")

#Export table - this one fails because of duplicated col_keys: 1 (N=2)
t1flex(score.t) %>% 
      save_as_docx(path = paste0("~/ExpoEnfants/tables/", score.t, ".docx"))
`
