### ISSUE TITLE
Code for adding to RMarkdown

### ISSUE THREAD

**Issue by michaelpawlus** [benjaminrich/table1#6]
Hello. 

First: great package. I really like the design.

You mention that this package is meant to be used with RMarkdown however I am having some issues getting the table to render.

I found that the following works in a code chunk:

```
capture.output(table1(~gapminder$continent + gapminder$lifeExp + gapminder$gdpPercap, standalone = FALSE)) %>%
  paste(., collapse = '') %>%
  htmltools::HTML(.)
```

However, I imagine there is an easier way and I am sure I am missing something obvious. I tried just including the function and using the option `results='asis'` as mentioned in your notes but that doesn't quite work when I run it and I ended with the html tags in the output.

**Comment by benjaminrich** [comment]
I'm really glad you like the package. I suggest you take a look at the [source of the vignette](https://raw.githubusercontent.com/benjaminrich/table1/master/vignettes/table1-examples.Rmd) for an example of how it is supposed to work in an rmarkdown context.

The 2 important things to remember are:
1. Specify a css file in the yaml header to style your table (otherwise it will look horrible).  You can grab the [style.css](https://raw.githubusercontent.com/benjaminrich/table1/master/vignettes/style.css) file in the vignette folder as a starting point and modify it as needed.
2. Use the results='asis' chunk option (I'm not sure why it isn't working for you).

If you are still having issues, then maybe you can post your .Rmd file?

**Comment by benjaminrich** [comment]
For example, your .Rmd file could look like this:

~~~~~~~~~~~~~~~~~~
---
title: Gapminder data (test table1)
output:
  html_document:
    css: style.css
---

```{r echo=F}
suppressPackageStartupMessages({
    library(table1)
    library(gapminder)
})
label(gapminder$continent) <- "Continent"
label(gapminder$lifeExp)   <- "Life expectency at birth (years)"
label(gapminder$gdpPercap) <- "GDP per capita (US$, inflation-adjusted)"
```

```{r echo=F, results='asis'}
table1(~ continent + lifeExp + gdpPercap, data=gapminder)
```
~~~~~~~~~~~~~~~~~~

**Comment by michaelpawlus** [comment]
Sorry for the delay. I’ll check out your example. Just didn’t get second to test it yet. Thanks for responding.

**Comment by michaelpawlus** [comment]
Just tested your example and it looks great. Not sure what the issue was before but helpful to know this works. Thanks again.
