### ISSUE TITLE
Susbscript and Superscript to variable names

### ISSUE THREAD

**Issue by chri360** [benjaminrich/table1#74]
I can't seem to find the option to add superscript to my variable name. I tried using the  expression function from base R and it was ignored.  I need to write CO^2 and many other compounds. Thanks for any help! Love the package :) 
![Screen Shot 2022-02-07 at 3 39 17 PM](https://user-images.githubusercontent.com/51720757/152859798-1826e9ef-d0e1-4428-806f-7587553eb3b1.png)

labels <- list(
  variables = list(Carbon_kt="Carbon Kt",
                   CO2_Equiv=expression("equivalents to CO"[2]),
                   Carbon_kt_per_KM2 = "CO per Km2",
                   Value_USD_per_KM2 = "USD per KM2"),
  groups=list("Removal rate","","")
)

**Comment by benjaminrich** [comment]
There are actually 2 ways of doing it. The best way in my opinion (because it seems more typographically correct), when it's available, is to use a Unicode symbol. You can find a list of them [here](https://unicode-table.com/en/sets/superscript-and-subscript-letters/). For instance, the Unicode symbol for subscript "2" is `2082`, and for superscript "2" it's `00B2`. The way you enter a Unicode symbol in an R string is `\U{xxxx}` where `xxxx` is the 4-digit code. Here's an example:

```r
library(table1)

set.seed(123)

d <- data.frame(co2=runif(20, 10, 100), km2=runif(20, 10, 100))

label(d$co2) <- "Equivalents to CO\U{2082}"
label(d$km2) <- "CO per Km\U{00B2}"

table1(~ co2 + km2, data=d)
```
![image](https://user-images.githubusercontent.com/17572252/152864415-e6e084ff-a36c-4153-80b4-7cdf1d5ab29d.png)

It works well in most cases, but not all letters have a Unicode superscript/subscript equivalent. The more general way is to use the HTML tags `<sub>...</sub>` for subscript and `<sup>...</sup>` for superscript. The `table1(...)` function produces HTML and passes these tags though, which then get interpreted by the browser (this was a design decision, to give all the flexibility that HTML provides). For the example above, that would give:

```r
label(d$co2) <- "Equivalents to CO<sub>2</sub>"
label(d$km2) <- "CO per Km<sup>2</sup>"

table1(~ co2 + km2, data=d)
```
![image](https://user-images.githubusercontent.com/17572252/152864463-ad8f2aeb-9425-4193-aa5c-556f5d089c8a.png)

It looks almost the same, except the symbols are a bit bigger. If you copy this and paste it into MS Word, you may need to adjust the font size afterwards because it might look too small (this has something to do which how copy-paste from the Chrome browser into MS Word works). Anyways, hope this helps!

**Comment by chri360** [comment]
Thanks so much for this! Super handy.

For now I only need to superscript and subscript numbers so hopefully I'll
be all set. This was extremely helpful, I'll keep it in my markdown
notebook for future use.

Again, thanks for the awesome package. :)


Christina N. De Jesús Villanueva
